// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"praktikum/handler"
	"praktikum/repository"
	"praktikum/service"
	"praktikum/worker"
)

// Injectors from wire.go:

func InitializedApplication() *Application {
	db := NewDatabase()
	blackListedTokenRepository := repository.NewBlackListedTokenRepository(db)
	groupMiddleware := NewGroupMiddleware(blackListedTokenRepository)
	userRepository := repository.NewUserRepository()
	authService := service.NewAuthService(db, userRepository, blackListedTokenRepository)
	authHandler := handler.NewAuthHandler(authService)
	orderRepository := repository.NewOrderRepository()
	productRepository := repository.NewProductRepository()
	orderItemRepository := repository.NewOrderItemRepository()
	orderService := service.NewOrderService(db, orderRepository, userRepository, productRepository, orderItemRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	orderItemService := service.NewOrderItemService(db, orderItemRepository)
	analyticsHandler := handler.NewAnaliticsHandler(orderItemService)
	engine := NewRouter(groupMiddleware, authHandler, orderHandler, analyticsHandler)
	tokenCleanupWorker := worker.NewTokenCleanupWorker(db, blackListedTokenRepository)
	application := NewApplication(engine, tokenCleanupWorker)
	return application
}
