// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"ujian3/delivery"
	"ujian3/repository"
	"ujian3/usecase"
)

// Injectors from wire.go:

func InitializedApplication() *Application {
	db := NewDatabase()
	blackListedTokenRepository := repository.NewBlackListedTokenRepository(db)
	groupMiddleware := NewGroupMiddleware(blackListedTokenRepository)
	userRepository := repository.NewUserRepository(db)
	employeeRepository := repository.NewEmployeeRepository(db)
	authUsecase := usecase.NewAuthUsecase(userRepository, employeeRepository)
	authHandler := delivery.NewAuthHandler(authUsecase)
	engine := NewRouter(groupMiddleware, authHandler)
	application := NewApplication(engine)
	return application
}
