// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"ujian2_rematch/handler"
	"ujian2_rematch/repository"
	"ujian2_rematch/service"
)

// Injectors from wire.go:

func InitializedApplication() *Application {
	db := NewDatabase()
	repositoryManager := repository.NewRepositoryManager(db)
	authService := service.NewAuthService(repositoryManager)
	authHandler := handler.NewAuthHandler(authService)
	departmentService := service.NewDepartmentService(repositoryManager)
	departmentHandler := handler.NewDepartmentHandler(departmentService)
	positionService := service.NewPositionService(repositoryManager)
	positionHandler := handler.NewPositionHandler(positionService)
	employeeService := service.NewEmployeeService(repositoryManager)
	employeeHandler := handler.NewEmployeeHandler(employeeService)
	engine := NewRouter(authHandler, departmentHandler, positionHandler, employeeHandler)
	application := NewApplication(engine)
	return application
}
