// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"ujian2_rematch/handler"
	"ujian2_rematch/middleware"
	"ujian2_rematch/repository"
	"ujian2_rematch/service"
	"ujian2_rematch/worker"
)

// Injectors from wire.go:

func InitializedApplication() *Application {
	db := NewDatabase()
	repositoryManager := repository.NewRepositoryManager(db)
	middlewareManager := middleware.NewMiddlewareManager(repositoryManager)
	authService := service.NewAuthService(repositoryManager)
	authHandler := handler.NewAuthHandler(authService)
	departmentService := service.NewDepartmentService(repositoryManager)
	departmentHandler := handler.NewDepartmentHandler(departmentService)
	positionService := service.NewPositionService(repositoryManager)
	positionHandler := handler.NewPositionHandler(positionService)
	employeeService := service.NewEmployeeService(repositoryManager)
	employeeHandler := handler.NewEmployeeHandler(employeeService)
	attendanceService := service.NewAttendanceService(repositoryManager)
	attendanceHandler := handler.NewAttendanceHandler(attendanceService)
	engine := NewRouter(middlewareManager, authHandler, departmentHandler, positionHandler, employeeHandler, attendanceHandler)
	tokenCleanupWorker := worker.NewTokenCleanupWorker(repositoryManager)
	application := NewApplication(engine, tokenCleanupWorker)
	return application
}
