@baseUrl = http://localhost:8080
@employees = {{baseUrl}}/employees

### Create
POST {{employees}} HTTP/1.1
Content-Type: : application/json

{
    "nik": "123456789",
    "full_name": "Emp 1",
    "email": "emp1@gmail.com",
    "department_id": 1,
    "position_id": 1
}

### Find By ID
GET {{employees}}/1 HTTP/1.1

### Find All
GET {{employees}} HTTP/1.1

### Update
PUT {{employees}}/1 HTTP/1.1
Content-Type: : application/json

{
    "nik": "123456789",
    "full_name": "Emp 2",
    "email": "emp1@gmail.com",
    "department_id": 1,
    "position_id": 1
}