// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/gin-gonic/gin"
	"praktikum/handler"
	"praktikum/repository"
	"praktikum/service"
)

// Injectors from wire.go:

func InitializedServer() *gin.Engine {
	db := NewDatabase()
	orderRepository := repository.NewOrderRepository()
	userRepository := repository.NewUserReposutory()
	productRepository := repository.NewProductRepository()
	orderItemRepository := repository.NewOrderItemRepository()
	orderService := service.NewOrderService(db, orderRepository, userRepository, productRepository, orderItemRepository)
	orderHandler := handler.NewOrderHandler(orderService)
	engine := NewRouter(orderHandler)
	return engine
}
